import path from "node:path";

import { Command } from "commander";

import { buildStructure } from "../../application/use-cases/build-structure";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { printJson } from "../presenters/json-presenter";

export function createBuildStructureCommand(): Command {
  return new Command("build-structure")
    .description("Build TOC, sections index, and per-section content nodes from normalized pages")
    .argument("<workspace>", "Workspace directory generated by init")
    .action(async (workspace: string) => {
      const workspaceDir = path.resolve(workspace);
      const store = new LocalFsArtifactStore();
      const result = await buildStructure(store, { workspaceDir });

      printJson({
        ok: true,
        workspaceDir,
        tocFile: result.tocFile,
        sectionsFile: result.sectionsFile,
        sectionCount: result.sectionCount,
        nodeCount: result.nodeCount,
        pageCount: result.pageCount,
      });
    });
}

