import path from "node:path";

import { Command } from "commander";

import type { DocumentMetadata } from "../../domain/models/manifest";
import type { Manifest } from "../../domain/models/manifest";
import { extractImages } from "../../application/use-cases/extract-images";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { PinoLoggerAdapter } from "../../infrastructure/adapters/logger/pino-logger-adapter";
import { parsePageRange } from "../../shared/utils/page-range";
import { printJson } from "../presenters/json-presenter";

export function createExtractImagesCommand(): Command {
  return new Command("extract-images")
    .description("Crop figure images from rendered pages using normalized image blocks")
    .argument("<workspace>", "Workspace directory generated by init")
    .option("--pages <range>", "Page range, example: 1-20")
    .action(async (workspace: string, options: { pages?: string }) => {
      const workspaceDir = path.resolve(workspace);
      const store = new LocalFsArtifactStore();
      const document = await store.readJson<DocumentMetadata>(path.join(workspaceDir, "document.json"));
      const manifest = await store.readJson<Manifest>(path.join(workspaceDir, "manifest.json"));
      const range = parsePageRange(options.pages, document.numPages ?? 1);
      const { SharpImageCropper } = await import("../../infrastructure/adapters/storage/sharp-image-cropper");

      const result = await extractImages(
        store,
        new SharpImageCropper(),
        new PinoLoggerAdapter(),
        {
          workspaceDir,
          manifest,
          startPage: range.startPage,
          endPage: range.endPage,
        },
      );

      printJson({
        ok: true,
        extractedImages: result.assets.length,
        pageRange: range,
      });
    });
}
