import path from "node:path";

import { Command } from "commander";

import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { loadManifest, loadToc } from "../../application/services/workspace-reader";
import { printJson } from "../presenters/json-presenter";

export function createInspectTocCommand(): Command {
  return new Command("inspect-toc")
    .description("Show the built TOC tree")
    .argument("<workspace>", "Workspace directory generated by init")
    .action(async (workspace: string) => {
      const workspaceDir = path.resolve(workspace);
      const artifactStore = new LocalFsArtifactStore();
      const manifest = await loadManifest(artifactStore, workspaceDir);
      const toc = await loadToc(artifactStore, workspaceDir, manifest);

      printJson({
        ok: true,
        toc,
      });
    });
}

