import path from "node:path";

import { Command } from "commander";

import type { Manifest } from "../../domain/models/manifest";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { loadPage } from "../../application/services/workspace-reader";
import { printJson } from "../presenters/json-presenter";

export function createInspectPageCommand(): Command {
  return new Command("inspect-page")
    .description("Show normalized page JSON for a specific page")
    .argument("<workspace>", "Workspace directory generated by init")
    .requiredOption("--page <number>", "Page number")
    .action(async (workspace: string, options: { page: string }) => {
      const workspaceDir = path.resolve(workspace);
      const artifactStore = new LocalFsArtifactStore();
      const manifest = await artifactStore.readJson<Manifest>(path.join(workspaceDir, "manifest.json"));
      const page = await loadPage(artifactStore, workspaceDir, manifest, Number(options.page));

      printJson({
        ok: true,
        page,
      });
    });
}

