import path from "node:path";

import { Command } from "commander";

import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import {
  findSection,
  loadManifest,
  loadSectionNodes,
  loadSections,
  loadToc,
} from "../../application/services/workspace-reader";
import { printJson } from "../presenters/json-presenter";

export function createInspectSectionCommand(): Command {
  return new Command("inspect-section")
    .description("Show one section and its content nodes by section id, ordinal, or title")
    .argument("<workspace>", "Workspace directory generated by init")
    .requiredOption("--section <value>", "Section id, ordinal, or title")
    .action(async (workspace: string, options: { section: string }) => {
      const workspaceDir = path.resolve(workspace);
      const artifactStore = new LocalFsArtifactStore();
      const manifest = await loadManifest(artifactStore, workspaceDir);
      const toc = await loadToc(artifactStore, workspaceDir, manifest);
      const sections = await loadSections(artifactStore, workspaceDir, manifest);
      const section = findSection(sections, toc, options.section);

      if (!section) {
        throw new Error(`Section not found: ${options.section}`);
      }

      const nodes = await loadSectionNodes(workspaceDir, section);
      printJson({
        ok: true,
        section,
        nodes,
      });
    });
}

