import path from "node:path";

import { Command } from "commander";

import type { Manifest } from "../../domain/models/manifest";
import { normalizePages } from "../../application/use-cases/normalize-pages";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { parsePageRange } from "../../shared/utils/page-range";
import { printJson } from "../presenters/json-presenter";

export function createNormalizePagesCommand(): Command {
  return new Command("normalize-pages")
    .description("Convert raw OCR batch output into page JSON files")
    .argument("<workspace>", "Workspace directory generated by init")
    .requiredOption("--batch <file>", "Raw OCR batch JSON file")
    .requiredOption("--pages <range>", "Page range matching the batch, example: 1-20")
    .action(async (workspace: string, options: { batch: string; pages: string }) => {
      const workspaceDir = path.resolve(workspace);
      const store = new LocalFsArtifactStore();
      const manifest = await store.readJson<Manifest>(path.join(workspaceDir, "manifest.json"));
      const range = parsePageRange(options.pages, 1);

      const result = await normalizePages(store, {
        workspaceDir,
        manifest,
        startPage: range.startPage,
        rawBatchFile: path.resolve(options.batch),
      });

      printJson({
        ok: true,
        normalizedPages: result.pages.length,
        pageRange: range,
      });
    });
}
