import path from "node:path";

import { Command } from "commander";

import type { AppConfig } from "../../domain/models/config";
import type { DocumentMetadata, Manifest } from "../../domain/models/manifest";
import { getConfig } from "../../application/use-cases/get-config";
import { parsePages } from "../../application/use-cases/parse-pages";
import { BigModelOcrAdapter } from "../../infrastructure/adapters/ocr/bigmodel-ocr-adapter";
import { FileConfigRepository } from "../../infrastructure/adapters/config/file-config-repository";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { PinoLoggerAdapter } from "../../infrastructure/adapters/logger/pino-logger-adapter";
import { parsePageRange } from "../../shared/utils/page-range";
import { PdftoppmPdfRenderer } from "../../infrastructure/adapters/pdf/pdftoppm-pdf-renderer";
import { printJson } from "../presenters/json-presenter";

export function createParsePagesCommand(): Command {
  return new Command("parse-pages")
    .description("Call BigModel GLM-OCR and cache raw batch results")
    .argument("<workspace>", "Workspace directory generated by init")
    .option("--pages <range>", "Page range, example: 1-20")
    .option("--timeout-sec <seconds>", "Request timeout in seconds", "120")
    .action(async (workspace: string, options: { pages?: string; timeoutSec: string }) => {
      const workspaceDir = path.resolve(workspace);
      const store = new LocalFsArtifactStore();
      const logger = new PinoLoggerAdapter();
      const configRepo = new FileConfigRepository();
      const config: AppConfig = await getConfig(configRepo);
      const renderer = new PdftoppmPdfRenderer();
      const document = await store.readJson<DocumentMetadata>(path.join(workspaceDir, "document.json"));
      const manifest = await store.readJson<Manifest>(path.join(workspaceDir, "manifest.json"));
      const fallbackEnd = document.numPages ?? (await renderer.getPageCount(document.sourcePdf));
      const range = parsePageRange(options.pages, fallbackEnd);

      const result = await parsePages(store, new BigModelOcrAdapter(config), logger, {
        workspaceDir,
        document,
        manifest,
        startPage: range.startPage,
        endPage: range.endPage,
        timeoutMs: Number(options.timeoutSec) * 1000,
      });

      printJson({
        ok: true,
        outputFile: result.outputFile,
        pageCount: result.pageCount,
        totalTokens: result.totalTokens,
        pageRange: range,
      });
    });
}
