import path from "node:path";

import { Command } from "commander";

import type { ContentNodeType } from "../../domain/models/content-node";
import { queryNodes } from "../../application/services/workspace-reader";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { printJson } from "../presenters/json-presenter";

const allowedTypes: ContentNodeType[] = ["heading", "paragraph", "formula", "figure", "table"];

export function createQueryCommand(): Command {
  return new Command("query")
    .description("Query content nodes by section, type, keyword, or page")
    .argument("<workspace>", "Workspace directory generated by init")
    .option("--section <value>", "Section id, ordinal, or title")
    .option("--type <type>", "Node type")
    .option("--keyword <term>", "Keyword to search in nodes")
    .option("--page <number>", "Limit to a specific page")
    .option("--limit <number>", "Maximum number of matches", "20")
    .action(
      async (
        workspace: string,
        options: {
          section?: string;
          type?: string;
          keyword?: string;
          page?: string;
          limit: string;
        },
      ) => {
        if (options.type && !allowedTypes.includes(options.type as ContentNodeType)) {
          throw new Error(`Invalid type: ${options.type}. Expected one of ${allowedTypes.join(", ")}.`);
        }

        const workspaceDir = path.resolve(workspace);
        const artifactStore = new LocalFsArtifactStore();
        const matches = await queryNodes(artifactStore, workspaceDir, {
          section: options.section,
          type: options.type as ContentNodeType | undefined,
          keyword: options.keyword,
          page: options.page ? Number(options.page) : undefined,
          limit: Number(options.limit),
        });

        printJson({
          ok: true,
          count: matches.length,
          matches,
        });
      },
    );
}

