import path from "node:path";

import { Command } from "commander";

import type { DocumentMetadata, Manifest } from "../../domain/models/manifest";
import { renderPages } from "../../application/use-cases/render-pages";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { PdftoppmPdfRenderer } from "../../infrastructure/adapters/pdf/pdftoppm-pdf-renderer";
import { PinoLoggerAdapter } from "../../infrastructure/adapters/logger/pino-logger-adapter";
import { parsePageRange } from "../../shared/utils/page-range";
import { printJson } from "../presenters/json-presenter";

export function createRenderPagesCommand(): Command {
  return new Command("render-pages")
    .description("Render PDF pages into page_renders PNG files")
    .argument("<workspace>", "Workspace directory generated by init")
    .option("--pages <range>", "Page range, example: 1-20")
    .option("--dpi <dpi>", "Render DPI", "160")
    .action(async (workspace: string, options: { pages?: string; dpi: string }) => {
      const workspaceDir = path.resolve(workspace);
      const store = new LocalFsArtifactStore();
      const logger = new PinoLoggerAdapter();
      const renderer = new PdftoppmPdfRenderer();
      const document = await store.readJson<DocumentMetadata>(path.join(workspaceDir, "document.json"));
      const manifest = await store.readJson<Manifest>(path.join(workspaceDir, "manifest.json"));
      const fallbackEnd = document.numPages ?? (await renderer.getPageCount(document.sourcePdf));
      const range = parsePageRange(options.pages, fallbackEnd);

      const result = await renderPages(store, renderer, logger, {
        workspaceDir,
        document,
        manifest,
        startPage: range.startPage,
        endPage: range.endPage,
        dpi: Number(options.dpi),
      });

      printJson({
        ok: true,
        renderedPages: result.rendered.length,
        pageCount: result.pageCount,
        pageRange: range,
      });
    });
}
