import path from "node:path";

import { Command } from "commander";

import { FileConfigRepository } from "../../infrastructure/adapters/config/file-config-repository";
import { PinoLoggerAdapter } from "../../infrastructure/adapters/logger/pino-logger-adapter";
import { startWorkspaceViewerServer } from "../../infrastructure/adapters/server/workspace-viewer-server";
import { LocalFsArtifactStore } from "../../infrastructure/adapters/storage/local-fs-artifact-store";
import { printJson } from "../presenters/json-presenter";

function keepServerAlive(server: import("node:http").Server): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    let closing = false;

    const shutdown = () => {
      if (closing) {
        return;
      }
      closing = true;
      server.close(() => {
        resolve();
      });
    };

    process.once("SIGINT", shutdown);
    process.once("SIGTERM", shutdown);
    server.once("close", resolve);
    server.once("error", reject);
  });
}

export function createViewCommand(): Command {
  return new Command("view")
    .description("Host a local Web UI for browsing one parsed PDF workspace")
    .argument("<workspace>", "Workspace directory generated by init/build commands")
    .option("--port <port>", "Port to listen on", "3211")
    .option("--host <host>", "Host to listen on", "127.0.0.1")
    .action(async (workspace: string, options: { port: string; host: string }) => {
      const workspaceDir = path.resolve(workspace);
      const store = new LocalFsArtifactStore();
      const configRepository = new FileConfigRepository();
      const logger = new PinoLoggerAdapter();
      const port = Number(options.port);

      const started = await startWorkspaceViewerServer(store, configRepository, logger, {
        workspaceDir,
        port,
        host: options.host,
      });

      printJson({
        ok: true,
        workspaceDir,
        url: started.url,
        host: options.host,
        port,
      });

      await keepServerAlive(started.server);
    });
}
